name: pyiron_workflow_atomistics
channels:
  - conda-forge

dependencies:
  # Core Python version
  - python>=3.9,<3.13

  # Conda-forge packages
  - numpy<2.0.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - ase>=3.22.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pyiron_base=0.8.3
  - pip
  - pymatgen>=2024.8.8
  - pyiron_workflow
  - pyiron_snippets
